server:
  port: 8080
  servlet:
    context-path: /staticor-web-services

spring:
  application:
    name: staticor-web-services
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://140.238.226.217:3306/staticor_schema?createIfNotExists=true&useSSL=false
    username: dev
    password: 8XAJwUzUkM$v3uDiVmy5zeFDEs
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jackson:
    serialization:
      fail-on-empty-beans: false