#server:
#  port: 8080
#  servlet:
#    context-path: /staticor-web-services
#
#spring:
#  application:
#    name: staticor-web-services
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://140.238.226.217:3306/staticor_schema?createIfNotExists=true&useSSL=false
##    username: dev
##    password: 8XAJwUzUkM$v3uDiVmy5zeFDEs
##    driverClassName: oracle.jdbc.driver.OracleDriver
##    url: jdbc:oracle:thin:/@INTELLEXDEV
#    username: dev
#    password: 8XAJwUzUkM$v3uDiVmy5zeFDEs
#  jpa:
#    hibernate.ddl-auto: update
#    generate-ddl: true
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
##        dialect: org.hibernate.dialect.OracleDialect
#  jackson:
#    serialization:
#      fail-on-empty-beans: false

server:
  port: 8081
  servlet:
    context-path: /sme-credit-appraisal-services

spring:
  application:
    name: sme-credit-appraisal-project
  datasource:
    jndi-name: java:jboss/datasources/fusion-mcomxfusion_ds
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        show_sql: false
        format_sql: false